name: Auto Close Jira Ticket

on:
  pull_request:
    types: [closed]

jobs:
  close-jira-ticket:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Trouver la clé Jira dans le titre de la PR
        id: find_key
        run: |
          ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT

      - name: Fermer le ticket Jira (statut 'Terminé')
        if: steps.find_key.outputs.issue_key != ''
        run: |
          curl -X POST \
            -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"transition": {"id": "41"}}' \
            https://misoftdia-1744458055603.atlassian.net/rest/api/3/issue/${{ steps.find_key.outputs.issue_key }}/transitions
